export const ProjectsList = [
  {
    id: 1,
    title: "CAFE 4KEY IN WEB WITH VITE",
    desc: "A visually appealing, fast, and responsive Café Shop website built using Vite for lightning-fast development, CSS for styling, Framer Motion for smooth animations, and Parallax effects to create an immersive user experience.It is live on www.cafe4key.com Now!",
    img: ["cafe4key1.jpeg", "cafe4key2.jpg", "cafe4key3.jpg", "cafe4key4.jpg"],
    tech: ["react", "css", "framer-motion"],
    demo: "https://riyasteche.github.io/cafe4key-web/",
    code: "https://github.com/RiyasTeche/cafe4key-web/tree/main/src",
    techStack: [
      "⚡ Vite + React: For high-performance SPA development",
      "🎞️ Framer Motion – Smooth entrance animations and interactive transitions",
      "🌄 Parallax Effects – Subtle scroll-based movement to create depth and engagement",
    ],
    keyFeatures: [
      "Hero section with parallax background and animated call-to-action",
      "Smooth entrance animations for sections (menu, about, contact)",
      "Fast load times and optimized performance with Vite",
    ],
  },
  {
    id: 2,
    title: "WEB APP FOR MOSQUE AUTOMATION",
    desc: "A fully functional Human Resource Management (HRM) web application designed to streamline Mohalla enhabitance management, track HR data, and simplify internal workflows. Built with a Node.js backend, MongoDB database, and full user login and authentication system.",
    img: ["masjid1.jpg", "masjid2.jpeg"],
    tech: ["react", "css", "navigation", "mongo"],
    demo: "",
    code: "https://github.com/RiyasTeche/masjid-soft/tree/master/masjid-client",
    techStack: [
      "⚡ Frontend: React",
      "Backend: Node.js, Express.js",
      "Database: MongoDB (Mongoose)",
      "Authentication: JWT (JSON Web Tokens), Bcrypt",
    ],
    keyFeatures: [
      "User Authentication & Authorization",
      "Dashboard Functionality",
      "Enhabitance Management",
    ],
  },
  {
    id: 3,
    title: "WEB APP FOR NEXWAVE SHIPPING",
    desc: "Developed a modern, responsive web application for Nexwave Logistics, tailored to enhance user engagement and streamline digital operations. The app was built using cutting-edge front-end technologies including Vite and React, ensuring fast performance and a smooth development workflow.",
    img: [
      "nexwave1.jpg",
      "nexwave2.jpg",
      "nexwave3.jpg",
      "nexwave4.jpg",
      "nexwave5.jpg",
      "nexwave6.jpg",
    ],
    tech: ["react", "scss", "framer-motion", "navigation", "threejs"],
    demo: "https://riyasteche.github.io/nexwave/",
    code: "https://github.com/RiyasTeche/nexwave/tree/main/src",
    techStack: [
      "Vite + React: For high-performance SPA development",
      "SCSS: For scalable and modular styling",
      "Framer Motion: To implement smooth, dynamic UI animations",
      "Three.js: For interactive 3D elements and visualizations",
      "Responsive Design: Fully compatible across all screen sizes and devices",
    ],
    keyFeatures: [
      "Email Integration: Users can send inquiries and requests via built-in email functionality",
      "Gallery Components: Visually rich, customizable image galleries with interactive UI",
      "Animation & Interactivity: Engaging user experience with animated transitions and 3D visuals",
    ],
  },
  {
    id: 4,
    title: "MY PORTFOLIO",
    desc: "My refined portfolio Website ,animations,email integration,routers for page switching and parelex effects for smooth viewing experiance!",
    img: [
      "portfolio1.jpg",
      "portfolio2.jpg",
      "portfolio3.jpg",
      "portfolio4.jpg",
      "portfolio5.jpg",
      "portfolio6.jpg",
    ],
    tech: ["react", "css", "framer-motion", "navigation"],
    demo: "https://riyasteche.github.io/portfolio-web/",
    code: "https://github.com/RiyasTeche/portfolio-web/tree/main/src",
    techStack: [
      "⚡ Vite – Lightning-fast development and build tool",
      "🎨 CSS – Custom styling for clean and modern layout",
      "🎞️ Framer Motion – Smooth, elegant animations and page transitions",
      "📱 Responsive Design – Works flawlessly across all screen sizes",
    ],
    keyFeatures: [
      "Email Integration: Users can send inquiries and requests via built-in email functionality",
      "Fast load times and optimized for performance",
      "Animation & Interactivity: Engaging user experience with animated transitions and 3D visuals",
      "Clean navigation with animated scroll transitions"
    ],
  },
];
